[package]
name = "laufer"
authors = ["Alexander Korn <dev@lxnd.me>"]
version = "0.1.0"
license = "MIT"
license-file = "LICENSE"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
